/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
    const { nodes, materials } = useGLTF("/Intro2.glb");
    return (
        <group {...props} dispose={null}>
            <group
                position={[2.465, -0.056, -1.747]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.portique.geometry}
                    material={materials.New_Material_1}
                    position={[128.768, -179.599, -104.014]}
                    rotation={[-Math.PI / 2, -1.57, 0]}
                    scale={0.628}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.portique_1.geometry}
                    material={materials.New_Material_1}
                    position={[155.726, 550.395, -97.914]}
                    rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                    scale={0.673}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.portique__1_.geometry}
                    material={materials.New_Material_1}
                    position={[-79.574, -179.599, -104.014]}
                    rotation={[-Math.PI / 2, -1.57, 0]}
                    scale={0.628}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.portique__2_.geometry}
                    material={materials.New_Material_1}
                    position={[-288.574, -179.599, -104.014]}
                    rotation={[-Math.PI / 2, -1.57, 0]}
                    scale={0.628}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.portique__3_.geometry}
                    material={materials.New_Material_1}
                    position={[319.426, 1.995, -104.014]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.628}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.portique__4_.geometry}
                    material={materials.New_Material_1}
                    position={[319.426, 196.995, -104.014]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.628}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.portique__5_.geometry}
                    material={materials.New_Material_1}
                    position={[319.426, 420.995, -104.014]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.628}
                />
            </group>
            <group
                position={[8.689, -2.904, -5.713]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
            >
                <group position={[-685.972, 544.63, -302.792]}>
                    <group position={[315, -326, -32.9]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.GFX.geometry}
                            material={materials.Fire_Wood}
                            position={[-157.7, -40.5, 196.821]}
                            rotation={[-1.57, 0, 0]}
                            scale={65}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Birch_Tree_05.geometry}
                        material={materials.PP_Standard_Material}
                        position={[-253.641, 228, 39]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Birch_Tree_05__1_.geometry}
                        material={materials.PP_Standard_Material}
                        position={[48, 332, 60]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Birch_Tree_06.geometry}
                        material={materials.PP_Standard_Material}
                        position={[496.229, -455.812, 46]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Birch_Tree_06__1_.geometry}
                        material={materials.PP_Standard_Material}
                        position={[-354.302, -438.762, 94]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Birch_Tree_06__2_.geometry}
                        material={materials.PP_Standard_Material}
                        position={[570.123, 176.911, 63]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Mushroom_Fantasy_Purple_08.geometry}
                        material={materials.PP_Standard_Material}
                        position={[82.065, 269.867, 15.487]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Mushroom_Fantasy_Purple_08001.geometry}
                        material={materials.PP_Standard_Material}
                        position={[104.597, 199.322, 11.284]}
                        rotation={[0, 0, -1.354]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Mushroom_Fantasy_Purple_08002.geometry}
                        material={materials.PP_Standard_Material}
                        position={[51.725, 386.445, 1.9]}
                        rotation={[0, 0, -1.82]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Mushroom_Fantasy_Purple_08003.geometry}
                        material={materials.PP_Standard_Material}
                        position={[74.236, 316.994, 13.205]}
                        rotation={[-0.184, -0.04, 2.687]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Mushroom_Fantasy_Purple_08004.geometry}
                        material={materials.PP_Standard_Material}
                        position={[85.144, 388.347, -3.874]}
                        rotation={[-0.184, -0.04, 1.333]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Mushroom_Fantasy_Purple_08005.geometry}
                        material={materials.PP_Standard_Material}
                        position={[50.837, 198.269, 20.464]}
                        rotation={[-0.184, -0.04, 0.866]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Mushroom_Fantasy_Purple_08006.geometry}
                        material={materials.PP_Standard_Material}
                        position={[138.661, 301.498, 8.183]}
                        rotation={[-0.184, -0.04, 2.687]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Mushroom_Fantasy_Purple_08007.geometry}
                        material={materials.PP_Standard_Material}
                        position={[20.711, 294.316, 15.797]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Rock_Moss_Grown_09.geometry}
                        material={materials.PP_Standard_Material}
                        position={[-167.491, -570, 41]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Rock_Moss_Grown_09__1_.geometry}
                        material={materials.PP_Standard_Material}
                        position={[605.245, -164.121, 39]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Rock_Moss_Grown_09__2_.geometry}
                        material={materials.PP_Standard_Material}
                        position={[-569, 49.649, 20]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Rock_Moss_Grown_11.geometry}
                        material={materials.PP_Standard_Material}
                        position={[387.83, -669, 26]}
                        scale={0.558}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Rock_Moss_Grown_11__1_.geometry}
                        material={materials.PP_Standard_Material}
                        position={[-203, 549, 18]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Rock_Pile_Forest_Moss_05.geometry}
                        material={materials.PP_Standard_Material}
                        position={[211.043, 642, 89.741]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Rock_Pile_Forest_Moss_10.geometry}
                        material={materials.PP_Standard_Material}
                        position={[-579, 493, -24.402]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Rock_Pile_Forest_Moss_10__1_.geometry}
                        material={materials.PP_Standard_Material}
                        position={[-639, -263.188, 73]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Tree_02.geometry}
                        material={materials.PP_Standard_Material}
                        position={[151.65, 144.396, 39]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Tree_02__1_.geometry}
                        material={materials.PP_Standard_Material}
                        position={[-266.099, -80.005, 188]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.PP_Tree_10.geometry}
                        material={materials.PP_Standard_Material}
                        position={[94.495, -493.119, 24]}
                    />
                </group>
                <group position={[-685.972, 544.63, -302.792]} />
                <group position={[-622.398, 396.635, -284.778]}>
                    <group
                        position={[-444.7, -266.5, -119.989]}
                        rotation={[0, 0, -0.687]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube_6.geometry}
                            material={materials.WOOHOOD}
                            position={[-25.072, 80.131, 44.465]}
                            scale={[0.891, 0.097, 0.359]}
                        >
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.text_5.geometry}
                                material={materials.LiberationSans_SDF_Material}
                                position={[8.5, 58, -376]}
                                rotation={[0, 0, -3.01]}
                                scale={[0.891, 0.097, 2]}
                            />
                        </mesh>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder_5.geometry}
                            material={materials.WOOHOOD}
                            position={[-29.932, 68.841, 79.955]}
                            scale={[0.151, 0.179, 0.58]}
                        />
                    </group>
                    <group
                        position={[-148.892, -239, -146.414]}
                        rotation={[0, 0, -0.102]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube_1.geometry}
                            material={materials.WOOHOOD}
                            position={[-25.072, 80.131, 44.465]}
                            scale={[0.891, 0.097, 0.359]}
                        >
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.text.geometry}
                                material={materials.LiberationSans_SDF_Material}
                                position={[8.5, 58, -376]}
                                rotation={[0, 0, -3.01]}
                                scale={[0.891, 0.097, 2]}
                            />
                        </mesh>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder.geometry}
                            material={materials.WOOHOOD}
                            position={[-29.932, 68.841, 79.955]}
                            scale={[0.151, 0.179, 0.58]}
                        />
                    </group>
                    <group
                        position={[70.906, -233.365, -117.5]}
                        rotation={[0, 0, -0.055]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube_2.geometry}
                            material={materials.WOOHOOD}
                            position={[-25.072, 80.131, 44.465]}
                            scale={[0.891, 0.097, 0.359]}
                        >
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.text_1.geometry}
                                material={materials.LiberationSans_SDF_Material}
                                position={[8.5, 58, -376]}
                                rotation={[0, 0, -3.01]}
                                scale={[0.891, 0.097, 2]}
                            />
                        </mesh>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder_1.geometry}
                            material={materials.WOOHOOD}
                            position={[-29.932, 68.841, 79.955]}
                            scale={[0.151, 0.179, 0.58]}
                        />
                    </group>
                    <group
                        position={[412.5, -114.879, -119.989]}
                        rotation={[0, 0, 1.138]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube_3.geometry}
                            material={materials.WOOHOOD}
                            position={[-25.072, 80.131, 44.465]}
                            scale={[0.891, 0.097, 0.359]}
                        >
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.text_2.geometry}
                                material={materials.LiberationSans_SDF_Material}
                                position={[8.5, 58, -376]}
                                rotation={[0, 0, -3.01]}
                                scale={[0.891, 0.097, 2]}
                            />
                        </mesh>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder_2.geometry}
                            material={materials.WOOHOOD}
                            position={[-29.932, 68.841, 79.955]}
                            scale={[0.151, 0.179, 0.58]}
                        />
                    </group>
                    <group
                        position={[375.209, 140.097, -147.023]}
                        rotation={[-0.009, -0.003, 1.572]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube_4.geometry}
                            material={materials.WOOHOOD}
                            position={[-25.072, 80.131, 44.465]}
                            scale={[0.891, 0.097, 0.359]}
                        >
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.text_3.geometry}
                                material={materials.LiberationSans_SDF_Material}
                                position={[8.5, 58, -376]}
                                rotation={[0, 0, -3.01]}
                                scale={[0.891, 0.097, 2]}
                            />
                        </mesh>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder_3.geometry}
                            material={materials.WOOHOOD}
                            position={[-29.932, 68.841, 79.955]}
                            scale={[0.151, 0.179, 0.58]}
                        />
                    </group>
                    <group
                        position={[377.6, 351.8, -146.599]}
                        rotation={[0, 0, 1.65]}
                        scale={0.982}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube_5.geometry}
                            material={materials.WOOHOOD}
                            position={[-25.072, 80.131, 44.465]}
                            scale={[0.891, 0.097, 0.359]}
                        >
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.text_4.geometry}
                                material={materials.LiberationSans_SDF_Material}
                                position={[8.5, 57.999, -376]}
                                rotation={[0, 0, -3.01]}
                                scale={[0.891, 0.097, 2]}
                            />
                        </mesh>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder_4.geometry}
                            material={materials.WOOHOOD}
                            position={[-29.932, 68.841, 79.955]}
                            scale={[0.151, 0.179, 0.58]}
                        />
                    </group>
                    <group
                        position={[-25.512, 588.135, -141.506]}
                        rotation={[-0.01, 0, -2.52]}
                        scale={0.982}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube_7.geometry}
                            material={materials.WOOHOOD}
                            position={[-25.072, 80.131, 44.465]}
                            scale={[0.891, 0.097, 0.359]}
                        >
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.text_6.geometry}
                                material={materials.LiberationSans_SDF_Material}
                                position={[8.5, 58, -376]}
                                rotation={[0, 0, -3.01]}
                                scale={[0.891, 0.097, 2]}
                            />
                        </mesh>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder_6.geometry}
                            material={materials.WOOHOOD}
                            position={[-29.932, 68.841, 79.955]}
                            scale={[0.151, 0.179, 0.58]}
                        />
                    </group>
                </group>
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.PP_Grass_15.geometry}
                material={materials["PP_Standard_Material.002"]}
                position={[0, 0.075, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.PP_Grass_11.geometry}
                material={materials.New_Material_1}
                position={[0.161, 0.026, 0.108]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.001}
            />
            <group scale={13.269}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane_1.geometry}
                    material={materials.Material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane_2.geometry}
                    material={materials.Material}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/Intro2.glb");
